#!/bin/bash
set -e

if [ "$EUID" -ne 0 ]; then
  echo "Run this script as root"
  exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")
. "$HERE/config"

function install-bin()
{
	NAME=$1
	if [ -f "$BASE/$ALIAS/man/man1/$NAME.1" ]; then
		update-alternatives --quiet --install "/usr/bin/$NAME" "$NAME" "$BASE/$ALIAS/bin/$NAME" 100 --slave "/usr/share/man/man1/$NAME.1" "$NAME.1" "$BASE/$ALIAS/man/man1/$NAME.1"
	else
		update-alternatives --quiet --install "/usr/bin/$NAME" "$NAME" "$BASE/$ALIAS/bin/$NAME" 100
	fi
}

function install-lib()
{
	NAME=$1
	SRC=$2
	LOCATION=$3
	update-alternatives --quiet --install "$LOCATION" "$NAME" "$BASE/$ALIAS/jre/lib/amd64/$SRC" 100
}

if [ ! -d "$BASE/$DIR" ]; then
	cd /tmp
	
	# Download
	if [ ! -f "$ARCHIVE.tar.gz" ]; then
		wget --no-check-certificate -c --header "Cookie: oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/$SITE/$ARCHIVE.tar.gz"
	fi

	# Extract
	cd /tmp
	tar xzvf "$ARCHIVE.tar.gz"
	
	# Move
	mkdir -p "$BASE"
	mv "$DIR" "$BASE"
	chown -R root:root "$BASE/$DIR"

	# Alias
	rm -f "$BASE/$ALIAS"
	cd "$BASE"
	ln -sf "$DIR" "$ALIAS"
	
	# Generate jinfo

	JINFO="$BASE/.java-8-oracle.jinfo"
	rm -f "$JINFO"

	# Header
	echo "name=java-8-oracle" >> "$JINFO"
	echo "priority=1000" >> "$JINFO"
	echo "section=main" >> "$JINFO"
	echo "" >> "$JINFO"

	# JRE items
	for NAME in "$BASE/$ALIAS/jre/bin/"*; do
		BASENAME=$(basename "$NAME")
		echo "jre $BASENAME $NAME" >> "$JINFO"
	done

	# An extra JRE item in lib
	echo "jre jexec /usr/lib/jvm/java-8-oracle/jre/lib/jexec" >> "$JINFO"

	# JDK items
	for NAME in "$BASE/$ALIAS/bin/"*; do
		BASENAME=$(basename "$NAME")
		# Make sure it is not already listed as a JRE item
		if [ ! -f "$BASE/$ALIAS/jre/bin/$BASENAME" ]; then
			echo "jdk $BASENAME $NAME" >> "$JINFO"
		fi
	done

	# Plugin items
	echo "plugin mozilla-javaplugin.so /usr/lib/jvm/java-8-oracle/jre/lib/amd64/libnpjp2.so" >> "$JINFO"

	set +e

	# Alternatives

	for NAME in "$BASE/$ALIAS/bin/"*; do
		install-bin $(basename "$NAME")
	done

	install-lib xulrunner-1.9-javaplugin.so libnpjp2.so /usr/lib/xulrunner-addons/plugins/libjavaplugin.so
	install-lib mozilla-javaplugin.so libnpjp2.so /usr/lib/mozilla/plugins/libjavaplugin.so
	
	update-java-alternatives -s "$ALIAS"
fi
